export const BANNED_KEYWORDS: string[] = [
  'weapon', 'gun', 'firearm', 'knife', 'bomb', 'explosive', 'grenade', 'ammunition',
  'murder', 'kill', 'assassinate', 'terrorism', 'blood', 'torture', 'shoot', 'massacre',
  'sniper', 'warfare', 'suicide', 'execution',
  'drugs', 'cocaine', 'heroin', 'meth', 'ecstasy', 'opioid', 'weed', 'marijuana',
  'cannabis', 'LSD', 'crack', 'hashish', 'smoke', 'injection', 'overdose',
  'drugdealer', 'psychedelic',
  'adult', 'porn', 'sex', 'xxx', 'nude', 'erotic', 'fetish', 'strip', 'escort',
  'prostitute', 'brothel', 'incest', 'rape', 'nsfw', 'bdsm', 'masturbate', 'hentai',
  'orgy', 'camgirl', 'onlyfans', 'sextape',
  'gambling', 'casino', 'poker', 'betting', 'lottery', 'jackpot', 'roulette',
  'slotmachine', 'bookmaker', 'sportsbet', 'blackjack',
  'scam', 'fraud', 'phishing', 'hacking', 'malware', 'ransomware', 'fakeid',
  'counterfeit', 'spoofing', 'forgery', 'steal', 'theft', 'spyware',
  'creditcard', 'darkweb',
  'hate', 'racism', 'homophobia', 'terror', 'nazi', 'isis', 'extremism',
  'genocide', 'slavery', 'lynch', 'hatecrime', 'antisemitic', 'whitepower',
  'selfharm', 'cutting', 'killmyself', 'hang', 'depress', 'overdose',
  'jump', 'die', 'noose',
  'humantrafficking', 'smuggling', 'illegal', 'kidnap', 'blackmarket',
  'piracy', 'bribe', 'extortion', 'moneylaundering', 'cybercrime',
  'forged', 'underground', 'crime', 'criminal',
  'abortion', 'necrophilia', 'zoophilia', 'bestiality', 'pedophile',
  'childporn', 'underage', 'molest', 'mutilation', 'snuff',
  // Arabic keywords
  'سلاح', 'مسدس', 'بندقية', 'قنبلة', 'متفجرات', 'ذخيرة', 'رصاص',
  'قتل', 'اغتيال', 'إرهاب', 'إرهابي', 'داعش', 'القاعدة', 'تفجير',
  'مخدرات', 'حشيش', 'هيروين', 'كوكايين', 'ميث', 'ماريجوانا', 'قنب', 'إكستاسي',
  'جنس', 'سكس', 'إباحي', 'بورنو', 'عري', 'دعارة', 'اغتصاب',
  'قمار', 'رهان', 'كازينو', 'يانصيب', 'مقامرة',
  'احتيال', 'تزوير', 'نصب', 'خداع', 'غسيل', 'تبييض', 'رشوة',
  'عنصرية', 'كراهية', 'نازية', 'تطرف',
  'انتحار', 'إيذاء', 'خنق', 'شنق',
];
