export type CategoryLink = {
  id: string;
  name: string;
  listingCategory: string;
};

export const marketplaceCategories: CategoryLink[] = [
  { id: 'programming', name: 'Programming', listingCategory: 'Web Development' },
  { id: 'design', name: 'Design', listingCategory: 'Graphic Design' },
  { id: 'music-audio', name: 'Music & Audio', listingCategory: 'Music Lessons' },
  { id: 'education', name: 'Education', listingCategory: 'Tutoring' },
  { id: 'fitness-wellness', name: 'Fitness & Wellness', listingCategory: 'Fitness Training' },
  { id: 'business-career', name: 'Business & Career', listingCategory: 'Consulting' },
  { id: 'photography-video', name: 'Photography & Video', listingCategory: 'Photography' },
  { id: 'home-living', name: 'Home & Living', listingCategory: 'Home Repair' },
  { id: 'study-buddy', name: 'Study buddy', listingCategory: 'Tutoring' },
  { id: 'modeling', name: 'Modeling', listingCategory: 'Photography & Video' },
  { id: 'pets-zone', name: 'Pets zone', listingCategory: 'Pet Care' },
  { id: 'ladies-hangout', name: 'Ladies hangout', listingCategory: 'Personal Care' },
  { id: 'delicious-food', name: 'Delicious food', listingCategory: 'Cooking' },
  { id: 'sporty', name: 'Sporty', listingCategory: 'Fitness Training' },
  { id: 'hear-me-out', name: "Hear me out / I'm all ears", listingCategory: 'Personal Care' },
  { id: 'babysitting', name: 'Babysitting', listingCategory: 'Personal Care' },
  { id: 'diet-guide', name: 'Diet guide', listingCategory: 'Fitness Training' },
  { id: 'carpooling', name: 'Share a ride / Carpooling', listingCategory: 'Transportation' },
  { id: 'beauty-and-makeup', name: 'Beauty and makeup', listingCategory: 'Beauty Services' },
  { id: 'hobby-and-happy', name: 'Hobby and happy', listingCategory: 'Arts & Crafts' },
  { id: 'business-consulting', name: 'Business consulting', listingCategory: 'Consulting' },
  { id: 'social-media-management', name: 'Social media platforms management', listingCategory: 'Consulting' },
  { id: 'content-creation', name: 'Content creation', listingCategory: 'Writing' },
  { id: 'other', name: 'Other', listingCategory: 'Other' },
  { id: 'graphic-design', name: 'Graphic Design', listingCategory: 'Graphic Design' },
  { id: 'web-development', name: 'Web Development', listingCategory: 'Web Development' },
  { id: 'home-repair', name: 'Home Repair', listingCategory: 'Home Repair' },
  { id: 'tech-support', name: 'Tech Support', listingCategory: 'Tech Support' },
  { id: 'tutoring', name: 'Tutoring', listingCategory: 'Tutoring' },
  { id: 'gardening', name: 'Gardening', listingCategory: 'Gardening' },
];

export const featuredMarketplaceCategories = marketplaceCategories.slice(0, 8);

export const serviceCategories = [
  'Graphic Design',
  'Gardening',
  'Web Development',
  'Home Repair',
  'Tech Support',
  'Tutoring',
  'Pet Care',
  'Photography',
  'Videography',
  'Repair Services',
  'Cooking',
  'Writing',
  'Music Lessons',
  'Fitness Training',
  'Event Planning',
  'Consulting',
  'Language Lessons',
  'Arts & Crafts',
  'Moving Help',
  'Beauty Services',
  'Personal Care',
  'Transportation',
  'Study buddy',
  'Modeling',
  'Pets zone',
  'Ladies hangout',
  'Delicious food',
  'Sporty',
  "Hear me out / I'm all ears",
  'Babysitting',
  'Diet guide',
  'Share a ride / Carpooling',
  'Beauty and makeup',
  'Hobby and happy',
  'Business consulting',
  'Social media platforms management',
  'Content creation',
  'Other',
] as const;