// Sync env values from frontend/.env.local to mobile/.env by mapping NEXT_PUBLIC_* -> EXPO_PUBLIC_*
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
// We're inside mobile/scripts now; repo root is two levels up
const root = path.resolve(__dirname, '..', '..');
const frontendEnvLocal = path.join(root, 'frontend', '.env.local');
const mobileEnv = path.join(root, 'mobile', '.env');

function parseDotEnv(content) {
  const out = {};
  for (const line of content.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    const val = trimmed.slice(eq + 1).trim();
    out[key] = val;
  }
  return out;
}

function stringifyEnv(obj) {
  const lines = [
    '# Generated by mobile/scripts/sync-env.mjs',
    '# Source: frontend/.env.local',
    '',
  ];
  for (const [k, v] of Object.entries(obj)) {
    lines.push(`${k}=${v}`);
  }
  lines.push('');
  return lines.join('\n');
}

function main() {
  if (!fs.existsSync(frontendEnvLocal)) {
    console.error('No frontend/.env.local found. Nothing to sync.');
    process.exit(0);
  }
  const src = fs.readFileSync(frontendEnvLocal, 'utf8');
  const srcVars = parseDotEnv(src);

  // Map NEXT_PUBLIC_FIREBASE_* -> EXPO_PUBLIC_FIREBASE_*
  const mappings = [
    'FIREBASE_API_KEY',
    'FIREBASE_AUTH_DOMAIN',
    'FIREBASE_PROJECT_ID',
    'FIREBASE_STORAGE_BUCKET',
    'FIREBASE_MESSAGING_SENDER_ID',
    'FIREBASE_APP_ID',
  ];

  const out = {};
  for (const key of mappings) {
    const webKey = `NEXT_PUBLIC_${key}`;
    const mobileKey = `EXPO_PUBLIC_${key}`;
    if (srcVars[webKey]) out[mobileKey] = srcVars[webKey];
  }

  // Emulators: default to true if not set
  if (!out['EXPO_PUBLIC_USE_EMULATORS']) out['EXPO_PUBLIC_USE_EMULATORS'] = 'true';
  // Sensible host default for Android Emulator (change to 127.0.0.1 for iOS)
  if (!out['EXPO_PUBLIC_EMULATOR_HOST']) out['EXPO_PUBLIC_EMULATOR_HOST'] = '10.0.2.2';

  // For local dev, FUNCTIONS_BASE is derived from EXPO_PUBLIC_EMULATOR_HOST (different
  // per platform: 10.0.2.2 for Android, 127.0.0.1 for iOS).  When the frontend
  // .env.local sets a NEXT_PUBLIC_FUNCTIONS_BASE pointing at a real hosted backend,
  // copy it across so the mobile dev build can reach the same environment.
  const webFnBase = srcVars['NEXT_PUBLIC_FUNCTIONS_BASE'];
  if (webFnBase && !webFnBase.includes('127.0.0.1') && !webFnBase.includes('localhost')) {
    out['EXPO_PUBLIC_FUNCTIONS_BASE'] = webFnBase;
    out['EXPO_PUBLIC_USE_EMULATORS'] = 'false';
  }

  fs.writeFileSync(mobileEnv, stringifyEnv(out), 'utf8');
  console.log('Synced env to mobile/.env');
}

main();
